config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :members, class_name: 'Admin::Member', controllers: {
    sessions: 'devise/members/sessions',
    registrations: 'devise/members/registrations'
  }
  # devise_for :members, controllers: {
  #   sessions: 'members/sessions'
  # }
  root 'home#index'

  namespace 'admin' do
    get '/home', to: 'home#index'

    resources :members
  end
end

app/models/admin.rb
# frozen_string_literal: true

module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/manager.rb
# frozen_string_literal: true

module Admin
  class Manager < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable
  end
end

app/models/admin/member.rb
# frozen_string_literal: true

module Admin
  class Member < ApplicationRecord
    require 'taiwanese_id_validator/twid_generator'

    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

    EMAIL_REGEX = /\A\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z]+\z/
    PHONE_REGEX = /\A09\d{8}\z/

    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable

    validates :name, presence: true
    validates :address, presence: true
    validates :birth_date, presence: true
    validates :email, presence: true,
                      format: { with: EMAIL_REGEX, message: I18n.t('.invalid_email') }
    validates :phone, presence: true,
                      format: { with: PHONE_REGEX, message: I18n.t('.invalid_phone') },
                      length: { is: 10, message: I18n.t('.invalid_phone') }
    validates :id_card_number, presence: true,
                               taiwanese_id: { allow_nil: false,
                                               allow_old: true,
                                               message: I18n.t('.invalid_id_card_number') }
    validates :password_confirmation, presence: true
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

module Admin
  class ApplicationController < ApplicationController
    before_action :authenticate_member!
  end
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

module Admin
  class HomeController < ApplicationController
    def index; end
  end
end

app/controllers/admin/members_controller.rb
# frozen_string_literal: true

module Admin
  class MembersController < ApplicationController
    include Pagy::Backend

    before_action :find_member, only: %i[edit update destroy]

    PERMITTED_ATTR = %i[name id_card_number email
                        phone address birth_date
                        password password_confirmation].freeze

    def index
      @pagy, @members = pagy(Admin::Member.order(id: :asc), items: 10)
    end

    def new
      @member = Admin::Member.new
    end

    def edit; end

    def create
      @member = Admin::Member.new(member_params)
      member = @member.save

      return redirect_to admin_members_path if member

      render :new
    end

    def update
      if @member.update(member_params)
        respond_to do |format|
          format.html { redirect_to admin_members_path, notice: t('.update.success') }
          format.turbo_stream
        end
      else
        render action: :update_failed
      end
    end

    def destroy
      @member.destroy

      respond_to do |format|
        format.html { redirect_to admin_members_path, notice: t('.success', name: @member.name) }
        format.turbo_stream
      end
    end

    private

    def member_params
      params[:admin_member].permit(PERMITTED_ATTR)
    end

    def find_member
      @member = Admin::Member.find_by(id: params[:id])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/admin/home_helper.rb
# frozen_string_literal: true

module Admin
  module HomeHelper
  end
end

app/helpers/admin/members_helper.rb
# frozen_string_literal: true

module Admin
  module MembersHelper
    def invalid_msg(model, attr)
      model.errors[attr].uniq.first
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/admin/members/_edit_form.html.erb
<%= form_with model: @member, class: 'edit-members-form table-header' do |f| %>

  <div class='table-cols name'>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'field_input edit-member-input-field' %>
    <span class="edit-members-error"><%= invalid_msg(@member, :name) %></span>
  </div>

  <div class='table-cols id-card-number'>
    <%= f.text_field :id_card_number, autofocus: true, autocomplete: "id_card_number", class: 'field_input edit-member-input-field' %>
    <span class="edit-members-error"><%= invalid_msg(@member, :id_card_number) %></span>
  </div>

  <span class='table-cols birth-date'>
    <%= f.date_field :birth_date, autofocus: true, autocomplete: "birth_date", class: 'field_input edit-member-input-field' %>
    <span class="edit-members-error"><%= invalid_msg(@member, :birth_date) %></span>
  </span>

  <span class='table-cols phone'>
    <%= f.phone_field :phone, autofocus: true, autocomplete: "phone", class: 'field_input edit-member-input-field' %>
    <span class="edit-members-error"><%= invalid_msg(@member, :phone) %></span>
  </span>

  <span class='table-cols email'>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'field_input edit-member-input-field' %>
    <span class="edit-members-error"><%= invalid_msg(@member, :email) %></span>
  </span>

  <span class='table-cols address'>
    <%= f.text_field :address, autofocus: true, autocomplete: "address", class: 'field_input edit-member-input-field' %>
    <span class="edit-members-error"><%= invalid_msg(@member, :address) %></span>
  </span>

  <div class='table-cols actions flex gap-x-2 '>
    <%= f.submit t('.submit'), class: 'edit-members-button' %>
    <div class='edit-members-button'><%= t('.cancel') %></div>
  </div>
<% end %>

app/views/admin/members/_members.html.erb
<div class="shadow-lg w-full">
  <div class='table-header items-center py-2 border-b border-b-black text-center'>
    <div class='table-cols name'>姓名</div>
    <div class='table-cols id-card-number'>身分證字號</div>
    <div class='table-cols birth-date'>出生年月日</div>
    <div class='table-cols phone'>電話</div>
    <div class='table-cols email'>電子信箱</div>
    <div class='table-cols address'>地址</div>
    <div class='table-cols actions'></div>
  </div>
  <% members.each do |member| %>
    <div class="even:bg-red-100">
      <%= turbo_frame_tag dom_id(member) do %>
        <%= render(Admin::MemberTableColumnComponent.new(member)) %>
      <% end %>
    </div>
  <% end %>
</div>

<div class='flex justify-center mt-4'>
  <%== pagy_nav(pagy) if pagy.pages > 1 %>
</div>

app/views/admin/members/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@member) do %>
<% end %>

app/views/admin/members/edit.html.erb
<%= turbo_frame_tag dom_id(@member) do %>
  <% render 'edit_form' %>
<% end %>

app/views/admin/members/index.erb
<div class="flex gap-x-4">
  <%= link_to t('.new_members'), new_admin_member_path, data: { turbo_frame: 'members_section' }, class: 'px-3 py-2 bg-blue-500 text-white font-medium rounded-lg hover:bg-blue-700' %>
  <!-- TODO:search -->
  <%= link_to t('.search_members'), '#', class: 'px-3 py-2 bg-blue-500 text-white font-medium rounded-lg hover:bg-blue-700' %>
</div>

<%= turbo_frame_tag 'members_section' do %>
  <%= render 'members', members: @members, pagy: @pagy %>
<% end %>

app/views/admin/members/new.html.erb
<%= turbo_frame_tag 'members_section' do %>
  <div class="new-members-title"><%= t('.new_member') %></div>

  <%= form_with model: @member, data: { turbo: false }, class: 'new-members-form' do |f| %>
    <div>
      <div class="new-members-field">
        <%= f.label :id_card_number %>
        <%= f.text_field :id_card_number, autofocus: true, autocomplete: "id_card_number", class: 'field_input' %>
      </div>
      <div class="new-members-error"><%= invalid_msg(@member, :id_card_number) %></div>
    </div>

    <div>
      <div class="new-members-field">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'field_input' %>
      </div>
      <div class="new-members-error"><%= invalid_msg(@member, :email) %></div>
    </div>

    <div>
      <div class="new-members-field">
        <%= f.label :phone %>
        <%= f.phone_field :phone, autofocus: true, autocomplete: "phone", class: 'field_input' %>
      </div>
      <div class="new-members-error"><%= invalid_msg(@member, :phone) %></div>
    </div>

    <div>
      <div class="new-members-field">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'field_input' %>
      </div>
      <div class="new-members-error"><%= invalid_msg(@member, :name) %></div>
    </div>

    <div>
      <div class="new-members-field">
        <%= f.label :address %>
        <%= f.text_field :address, autofocus: true, autocomplete: "address", class: 'field_input' %>
      </div>
      <div class="new-members-error"><%= invalid_msg(@member, :address) %></div>
    </div>

    <div>
      <div class="new-members-field">
        <%= f.label :birth_date %>
        <%= f.date_field :birth_date, autofocus: true, autocomplete: "birth_date", class: 'field_input' %>
      </div>
      <div class="new-members-error"><%= invalid_msg(@member, :birth_date) %></div>
    </div>

    <div>
      <div class="new-members-field">
        <%= f.label :password %>
        <% if @minimum_password_length %>
          <em class='text-sm m-auto'>(<%= t('.characters_minimum', length: @minimum_password_length) %>)</em>
        <% end %>
        <%= f.password_field :password, autocomplete: "new-password", class: 'field_input' %>
      </div>
      <div class="new-members-error"><%= invalid_msg(@member, :password) %></div>
    </div>

    <div>
      <div class="new-members-field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'field_input' %>
      </div>
      <div class="new-members-error"><%= invalid_msg(@member, :password_confirmation) %></div>
    </div>

    <%= f.submit t('.create_members'), class: 'new-members-button' %>
  <% end %>
<% end %>

app/views/admin/members/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@member) do %>
  <%= render(Admin::MemberTableColumnComponent.new(@member)) %>
<% end %>

app/views/admin/members/update_failed.html.erb
<%= turbo_frame_tag dom_id(@member) do %>
  <%= render 'edit_form' %>
<% end %>

app/views/home/index.html.erb
<h1 class="field">Home</h1>

app/views/layouts/_header.html.erb
<nav class='flex justify-between items-center w-full py-3 px-6 shadow-md'>
  <h1 class='text-3xl font-medium tracking-widest'>三芝港口慈航宮</h1>
  <ul class='flex items-center gap-x-20'>
    <li class='hover:border-2 hover:border-red-400 hover:cursor-pointer'>
      <%= link_to '會員管理', admin_members_path, class: 'px-2 py-1' %>
    </li>
    <li class='px-2 py-1 hover:border-2 hover:border-red-400 hover:cursor-pointer'>信眾管理</li>
    <li class='px-2 py-1 hover:border-2 hover:border-red-400 hover:cursor-pointer'>聖物管理</li>
    <li class='px-2 py-1 hover:border-2 hover:border-red-400 hover:cursor-pointer'>行程管理</li>
  </ul>
  <div>
    <% if current_member %>
      <%= current_member.name %>
      <%= link_to '登出', destroy_member_session_path, data: { turbo_method: 'delete' } %>
    <% elsif !request.controller_class.to_s.include?('Devise') %>
      <%= link_to '登入', new_member_session_path %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>三芝港口慈航宮</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="flex flex-col justify-center items-center gap-y-6">
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>